### ISSUE TITLE
Should build on schedule

### ISSUE THREAD

**Issue by apatel762** [apatel762/workspace#3]
Add the below snippet to the GitHub action:

```yaml
name: Create and publish a Container image

on:
  schedule:
    - cron: '0 0 * * TUE'  # build every Tuesday
```

(snippet taken from https://github.com/ublue-os/boxkit/blob/main/.github/workflows/build-boxkit.yml)
